# Example CPC Configuration File
# IMPORTANT: Include both CPC classes AND subgroups for comprehensive coverage

domains:
  quantum_computing:
    description: "Information processing based on quantum-mechanical phenomena"
    cpc_codes:
      # Primary quantum computing codes
      - code: "G06N10/20"
        description: "Models of quantum computing, e.g. quantum circuits or universal quantum computers"
      - code: "G06N10/40"
        description: "Physical realisations or architectures of quantum processors or components for manipulating qubits"
      - code: "G06N10/60"
        description: "Quantum algorithms, e.g. based on quantum optimisation, quantum Fourier or Hadamard transforms"
      - code: "G06N10/70"
        description: "Quantum error correction, detection or prevention, e.g. surface codes or magic state distillation"
      - code: "G06N10/80"
        description: "Quantum programming, e.g. interfaces, languages or software-development kits"
      
      # Additional relevant codes
      - code: "G06N10"
        description: "Quantum computing (general)"
      - code: "H04L9/0852"
        description: "Quantum key distribution"
      - code: "H04B10/70"
        description: "Quantum communication"
      - code: "H01L39/24"
        description: "Josephson junction devices"
      - code: "H01L39/22"
        description: "Superconducting devices with potential barriers"
      - code: "G01R33/035"
        description: "NMR quantum computing arrangements"
      - code: "B82Y10"
        description: "Nanotechnology for quantum computing"

user_inputs:
  companies:
    - International Business Machines
    - IBM
    - Google
  date_range:
    start_year: 2020
    end_year: 2024